import React, { createContext, useContext, useState } from 'react';

const translations = {
  nl: {
    dashboard: 'Dashboard',
    leads: 'Contacten',
    mailCampaigns: 'E-mailcampagnes',
    settings: 'Instellingen',
    agenda: 'Agenda',
    addLead: 'Nieuw Contact',
    totalLeads: 'Totaal Contacten',
    activeLeads: 'Aktive Trajecten',
    conversionRate: 'Conversieratio',
    searchPlaceholder: 'Zoek op bedrijf of e-mail...',
    upcoming: 'Binnenkort',
    overdue: 'Gecumuleerd',
    today: 'Vandaag',
    agendaDescription: 'Beheer hier wanneer u contact moet opnemen met welke klant.',
    quickTask: 'Snel Taak Toevoegen',
    companyPlaceholder: 'Zoek klant...',
    taskPlaceholder: 'Bijv. Offerte nabellen',
    agendaTaskLabel: 'Wat moet er gebeuren?',
    pickDate: 'Datum',
    pickTime: 'Tijd',
    addAsNew: 'als nieuwe klant toevoegen',
    createNewLead: 'Nieuwe lead aanmaken',
    completeTask: 'Voltooien',
    noTasks: 'Geen taken gepland',
    reminders: 'Herinneringen',
    notifications: 'Meldingen',
    reminder30m: 'Hatırlatıcı: Görev 30 dakika içinde!',
    reminderNow: 'Hatırlatıcı: Görev zamanı geldi!',
    sector: 'Branche',
    status: 'Fase',
    actions: 'Acties',
    allSectors: 'Alle Branches',
    new: 'Nieuwe Aanvraag',
    contacted: 'Gecontacteerd',
    interested: 'In Bespreking',
    customer: 'Klant Geworden',
    rejected: 'Geen Interesse',
    showingResultFor: 'Resultaat voor',
    clearFilter: 'Filter wissen',
    upcomingTasks: 'Komende Taken',
    language: 'Taal',
    dashboardDesc: 'Overzicht van uw leadgeneratie en conversiestatistieken.',
    recentActivity: 'Recente Activiteit',
    hotProspects: 'Warme Prospects',
    viewAll: 'Alles Bekijken',
    noProspects: 'Nog geen prospects. Voeg er een toe om ze hier te zien.',
    company: 'Bedrijf',
    email: 'E-mailadres',
    campaignsDesc: 'Ontwerp geautomatiseerde reeksen en volg de prestaties.',
    createCampaign: 'Campagne Maken',
    totalSent: 'Totaal Verzonden',
    avgOpenRate: 'Gem. Openingspercentage',
    avgClickRate: 'Gem. Klikpercentage',
    totalReplies: 'Totaal Antwoorden',
    recentCampaigns: 'Recente Campagnes',
    campaignName: 'Campagnenaam',
    sentTo: 'Verzonden naar',
    openRate: 'Openingspercentage',
    clickRate: 'Klikpercentage',
    dateRun: 'Uitvoeringsdatum',
    exportReport: 'Rapport Exporteren',
    duplicate: 'Dupliceren',
    sendNow: 'Nu Verzenden',
    campaignInternalName: 'Interne Campagnenaam',
    emailSubjectLine: 'Onderwerpregel E-mail',
    emailBody: 'E-mail Inhoud',
    audienceSettings: 'Doelgroepinstellingen',
    targetSector: 'Doelgroep Branche',
    targetStatus: 'Doelgroep Fase',
    estimatedAudience: 'Geschat Publiek',
    scheduleDelivery: 'Verzending Inplannen',
    saveDraft: 'Concept Opslaan',
    sendCampaign: 'Campagne Verzenden',
    scheduleCampaign: 'Campagne Inplannen',
    performanceSummary: 'Prestatiesamenvatting',
    subjectLine: 'Onderwerpregel',
    targetSegments: 'Doelgroepsegmenten',
    sendingAccount: 'Verzendaccount',
    tracking: 'Tracking',
    emailsWillBeSent: 'E-mails worden direct verzonden tenzij ingepland.',
    cancel: 'Annuleren',
    setDateAndTime: 'Datum & Tijd Instellen',
    leadsDesc: 'Beheer uw potentiële klanten en volg hun status.',
    exportCsv: 'CSV Exporteren',
    noLeadsFound: 'Geen contacten gevonden',
    tryAdjustingSearch: 'Probeer uw zoek- of filtercriteria aan te passen.',
    settingsDesc: 'Beheer uw accountvoorkeuren en applicatie-instellingen.',
    personalInformation: 'Persoonlijke Informatie',
    changeAvatar: 'Avatar Wijzigen',
    firstName: 'Voornaam',
    lastName: 'Achternaam',
    emailAddress: 'E-mailadres',
    saveChanges: 'Wijzigingen Opslaan',
    apiKeys: 'API-sleutels',
    manageKeys: 'Beheer sleutels voor externe systeemintegraties.',
    generateNewKey: 'Nieuwe Sleutel Genereren',
    name: 'Naam',
    tokenPreview: 'Token Voorbeeld',
    created: 'Aangemaakt',
    revoke: 'Intrekken',
    edit: 'Bewerken',
    delete: 'Verwijderen',
    pause: 'Pauzeren',
    resume: 'Hervatten',
    confirmDelete: 'Weet u zeker dat u dit item wilt verwijderen?',
    targetAudiencePreview: 'Doelgroep Voorbeeld',
    editCampaign: 'Campagne Bewerken',
    cancelSchedule: 'Schema Annuleren',
    tabProfile: 'Profiel',
    tabCompanyDetails: 'Bedrijfsgegevens',
    companyNameField: 'Bedrijfsnaam',
    websiteUrlField: 'Website URL',
    logoUploadField: 'Logo Uploaden',
    logoUploadHelp: 'PNG, JPG of SVG (max. 2MB).',
    addressField: 'Adres',
    addressPlaceholder: 'Straat, Huisnummer, Postcode, Stad',
    phoneField: 'Telefoonnummer',
    vatField: 'Btw-nummer (VAT)',
    kvkField: 'KvK-nummer',
    tabTeam: 'Teamleden',
    tabEmail: 'E-mail & Aflevering',
    tabNotifications: 'Meldingen',
    tabLeadManagement: 'Contactbeheer',
    tabBilling: 'Facturering & Verbruik',
    tabAutomation: 'Automatisering & Web-Scraper',
    tabEmailNav: 'E-mail & Aflevering',
    tabAutomationNav: 'Automatisering & Bot',
    emailConfig: 'SMTP E-mailconfiguratie',
    emailConfigDesc: 'Configureer uw uitgaande mailserver en e-mailhandtekening.',
    smtpHost: 'SMTP Host',
    smtpPort: 'SMTP Poort',
    senderName: 'Afzender Naam',
    defaultSignature: 'Standaard E-mailhandtekening',
    dailyLimit: 'Dagelijkse Verzendlimiet',
    spamPrevention: 'Spampreventie (Verlaag de verzendsnelheid)',
    teamMembers: 'Teamleden',
    addMember: 'Lid Toevoegen',
    role: 'Rol',
    admin: 'Beheerder',
    viewer: 'Kijker',
    invite: 'Uitnodigen',
    notificationsSettings: 'Meldingsvoorkeuren',
    emailOpens: 'Waarschuwing bij openen e-mail',
    emailClicks: 'Waarschuw bij klikken op links',
    weeklyReports: 'Wekelijkse samenvatting',
    realTimeAlerts: 'Realtime meldingen voor hete leads',
    leadManagementOptions: 'Beheer Labels en Fases',
    customSectors: 'Aangepaste Branches (Sectoren)',
    customStatuses: 'Aangepaste Statussen (Stages)',
    addTag: 'Label Toevoegen',
    billing: 'Abonnement & Facturatie',
    activePlan: 'Huidige Plan',
    currentUsage: 'Huidig Verbruik',
    emailsSentThisMonth: 'E-mails verzonden deze maand',
    invoiceHistory: 'Factuurgeschiedenis',
    automation: 'Automatisering en Scraper-bot',
    scraperBot: 'Configuratie Webscraper-bot',
    targetKeywords: 'Doelzoekwoorden (komma-gescheiden)',
    cronSchedule: 'Schraapschema (Bijv. Elke woensdag om 09:00)',
    autoVerify: 'Automatisch e-mailadressen verifiëren na het schrapen',
    runScraper: 'Scraper handmatig uitvoeren',
    replyToEmail: 'Antwoord-naar E-mail (Reply-To)',
    useSslTls: 'Gebruik SSL/TLS Encryptie',
    playPing: 'Speel "Ping" Melodie',
    playChime: 'Speel "Chime" Melodie',
    playPop: 'Speel "Pop" Melodie',
    upgradePlan: 'Plan Upgraden',
    downloadPdf: 'PDF Downloaden',
    amount: 'Bedrag',
    date: 'Datum',
    paid: 'Betaald',
    basicMode: 'Basis Modus',
    advancedMode: 'Geavanceerde Modus',
    frequency: 'Frequentie',
    time: 'Tijdstip',
    daily: 'Dagelijks',
    weekly: 'Wekelijks',
    monthly: 'Maandelijks',
    useProxy: 'Gebruik Roterende Proxy',
    headlessBrowser: 'Start Headless Browser (JS-Rendering)',
    aiIntegrations: 'AI & Automatisering Integraties',
    apiKey: 'API-sleutel',
    openaiDesc: 'Gebruik voor geavanceerde e-mailtekst generatie.',
    claudeDesc: 'Gebruik voor slimme sectoranalyse en samenvattingen.',
    geminiDesc: 'Gebruik voor grote hoeveelheden webdata-analyse.',
    getApiKey: 'Sleutel ophalen',
    connected: 'Verbonden',
    notConnected: 'Niet Verbonden',
    exportDestination: 'Export Bestemming',
    connectedAs: 'Verbonden als',
    manualLocation: 'Handmatige Locatie',
    googleDrive: 'Google Drive (Spreadsheets)',
    scraperSources: 'Scraper Bronnen',
    googleMaps: 'Google Maps',
    telefoonboek: 'Telefoonboek.nl',
    kvk: 'KVK.nl (Handelsregister)',
    addCustomSource: 'Aanvullende Bron Toevoegen',
    suggestions: 'Sleutelsuggesties',
    automaticDiscovery: 'Automatische Ontdekking',
    savedSources: 'Opgeslagen Bronnen',
    enterUrl: 'URL invoeren...',
    discoveryDesc: 'Laat de bot automatisch de beste lokale gidsen vinden.',
    suggestedForYou: 'Aanbevolen voor jou',
    highReliability: 'Hoge Betrouwbaarheid',
    localDirectories: 'Lokale Gidsen',
    verifiedSource: 'Geverifieerde Bron',
    dataQuality: 'Datakwaliteit',
    premiumSource: 'Premium Bron',
    leadEnrichment: 'Contact Verrijking',
    leadsWithMissingData: 'Contacten met ontbrekende gegevens',
    followUpPlanner: 'Follow-Up Planner',
    tabDataManagement: 'Gegevensbeheer',
    action: 'Actie',
    contactNow: 'Nu Contact Opnemen',
    noLogo: 'Geen Logo',
    cardHolder: 'Kaarthouder',
    cardNumber: 'Kaartnummer',
    expiryDate: 'Vervaldatum',
    paymentConfirmed: 'Betaling Bevestigd',
    manageTeamDescription: 'Beheer de toegangsniveaus voor uw teamleden.',
    notificationsDesc: 'Stel in voor welke acties u een melding wilt ontvangen.',
    leadManagementOptionsDesc: 'Beheer hier de labels en fases voor uw klantcontacten.',
    aiIntegrationsDesc: 'Koppel AI-providers voor slimme e-mailgeneratie.',
    apiKeysDesc: 'Beheer uw systeemtoegangssleutels voor API-gebruik.',
    dataExportDesc: 'Download een back-up van uw volledige systeemdata.'
  },
  en: {
    dashboard: 'Dashboard',
    leads: 'Leads',
    mailCampaigns: 'Mail Campaigns',
    settings: 'Settings',
    agenda: 'Agenda',
    addLead: 'Add Lead',
    totalLeads: 'Total Leads',
    activeLeads: 'Active Deals',
    conversionRate: 'Conversion Rate',
    searchPlaceholder: 'Search company or email...',
    upcoming: 'Upcoming',
    overdue: 'Overdue',
    today: 'Today',
    agendaDescription: 'Manage which customer to contact and when, right here.',
    quickTask: 'Add Quick Task',
    companyPlaceholder: 'Search customer...',
    taskPlaceholder: 'e.g. Call for offer',
    agendaTaskLabel: 'What needs to be done?',
    pickDate: 'Date',
    pickTime: 'Time',
    addAsNew: 'add as new customer',
    createNewLead: 'Create new lead',
    completeTask: 'Complete',
    noTasks: 'No tasks planned',
    reminders: 'Reminders',
    notifications: 'Notifications',
    reminder30m: 'Reminder: Task in 30 minutes!',
    reminderNow: 'Reminder: Task time reached!',
    sector: 'Sector',
    status: 'Status',
    actions: 'Actions',
    allSectors: 'All Sectors',
    new: 'New Lead',
    contacted: 'Contacted',
    interested: 'Interested',
    customer: 'Customer',
    rejected: 'Rejected',
    showingResultFor: 'Showing result for',
    clearFilter: 'Clear Filter',
    upcomingTasks: 'Upcoming Tasks',
    language: 'Language',
    dashboardDesc: 'Overview of your lead generation and conversion metrics.',
    recentActivity: 'Recent Activity',
    hotProspects: 'Hot Prospects',
    viewAll: 'View All',
    noProspects: 'No prospects yet. Add some to see them here.',
    company: 'Company',
    email: 'Email',
    campaignsDesc: 'Design automated outreach sequences and track performance.',
    createCampaign: 'Create Campaign',
    totalSent: 'Total Sent',
    avgOpenRate: 'Avg. Open Rate',
    avgClickRate: 'Avg. Click Rate',
    totalReplies: 'Total Replies',
    recentCampaigns: 'Recent Campaigns',
    campaignName: 'Campaign Name',
    sentTo: 'Sent To',
    openRate: 'Open Rate',
    clickRate: 'Click Rate',
    dateRun: 'Date Run',
    exportReport: 'Export Report',
    duplicate: 'Duplicate',
    sendNow: 'Send Now',
    campaignInternalName: 'Campaign Internal Name',
    emailSubjectLine: 'Email Subject Line',
    emailBody: 'Email Body',
    audienceSettings: 'Audience Settings',
    targetSector: 'Target Sector',
    targetStatus: 'Target Status',
    estimatedAudience: 'Estimated Audience',
    scheduleDelivery: 'Schedule Delivery',
    saveDraft: 'Save Draft',
    sendCampaign: 'Send Campaign',
    scheduleCampaign: 'Schedule Campaign',
    performanceSummary: 'Performance Summary',
    subjectLine: 'Subject Line',
    targetSegments: 'Target Segments',
    sendingAccount: 'Sending Account',
    tracking: 'Tracking',
    emailsWillBeSent: 'Emails will be sent immediately unless scheduled.',
    cancel: 'Cancel',
    setDateAndTime: 'Set Date & Time',
    leadsDesc: 'Manage your potential clients and track their status.',
    exportCsv: 'Export CSV',
    noLeadsFound: 'No leads found',
    tryAdjustingSearch: 'Try adjusting your search or filter requirements.',
    settingsDesc: 'Manage your account preferences and application settings.',
    personalInformation: 'Personal Information',
    changeAvatar: 'Change Avatar',
    firstName: 'First Name',
    lastName: 'Last Name',
    emailAddress: 'Email Address',
    saveChanges: 'Save Changes',
    apiKeys: 'API Keys',
    manageKeys: 'Manage keys for external system integrations.',
    generateNewKey: 'Generate New Key',
    name: 'Name',
    tokenPreview: 'Token Preview',
    created: 'Created',
    revoke: 'Revoke',
    edit: 'Edit',
    delete: 'Delete',
    pause: 'Pause',
    resume: 'Resume',
    confirmDelete: 'Are you sure you want to delete this item?',
    targetAudiencePreview: 'Target Audience Preview',
    editCampaign: 'Edit Campaign',
    cancelSchedule: 'Cancel Schedule',
    tabProfile: 'Profile',
    tabCompanyDetails: 'Company Details',
    companyNameField: 'Company Name',
    websiteUrlField: 'Website URL',
    logoUploadField: 'Upload Logo',
    logoUploadHelp: 'PNG, JPG or SVG (max. 2MB).',
    addressField: 'Business Address',
    addressPlaceholder: 'Street, Number, Zip, City',
    phoneField: 'Phone Number',
    vatField: 'VAT Number',
    kvkField: 'Chamber of Commerce (KVK)',
    tabTeam: 'Team Members',
    tabEmail: 'Email & Delivery',
    tabNotifications: 'Notifications',
    tabLeadManagement: 'Lead Management',
    tabBilling: 'Billing & Usage',
    tabAutomation: 'Automation & Bot',
    tabEmailNav: 'Email & Delivery',
    tabAutomationNav: 'Automation & Bot',
    emailConfig: 'SMTP Email Configuration',
    emailConfigDesc: 'Configure your outgoing mail server and email signature.',
    smtpHost: 'SMTP Host',
    smtpPort: 'SMTP Port',
    senderName: 'Sender Name',
    defaultSignature: 'Default Email Signature',
    dailyLimit: 'Daily Sending Limit',
    spamPrevention: 'Spam Prevention (Throttle sending speed)',
    teamMembers: 'Team Members',
    addMember: 'Add Member',
    role: 'Role',
    admin: 'Admin',
    viewer: 'Viewer',
    invite: 'Invite',
    notificationsSettings: 'Notification Preferences',
    emailOpens: 'Alert on email opens',
    emailClicks: 'Alert on link clicks',
    weeklyReports: 'Weekly summary report',
    realTimeAlerts: 'Real-time alerts for hot leads',
    leadManagementOptions: 'Manage Lead Tags and Stages',
    customSectors: 'Custom Industries (Sectors)',
    customStatuses: 'Custom Statuses (Stages)',
    addTag: 'Add Tag',
    billing: 'Subscription & Billing',
    activePlan: 'Active Plan',
    currentUsage: 'Current Usage',
    emailsSentThisMonth: 'Emails sent this month',
    invoiceHistory: 'Invoice History',
    automation: 'Automation and Scraper Bot',
    scraperBot: 'Web Scraper Bot Configuration',
    targetKeywords: 'Target Keywords (comma separated)',
    cronSchedule: 'Scraping Schedule (E.g. Every Wed at 09:00)',
    autoVerify: 'Auto-verify email addresses after scraping',
    runScraper: 'Run Scraper Manually',
    replyToEmail: 'Reply-To Email',
    useSslTls: 'Use SSL/TLS Encryption',
    playPing: 'Play "Ping" Melody',
    playChime: 'Play "Chime" Melody',
    playPop: 'Play "Pop" Melody',
    upgradePlan: 'Upgrade Plan',
    downloadPdf: 'Download PDF',
    amount: 'Amount',
    date: 'Date',
    paid: 'Paid',
    basicMode: 'Basic Mode',
    advancedMode: 'Advanced Mode',
    frequency: 'Frequency',
    time: 'Time',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    useProxy: 'Use Rotating Proxy',
    headlessBrowser: 'Run Headless Browser (JS Rendering)',
    aiIntegrations: 'AI & Automation Integrations',
    apiKey: 'API Key',
    openaiDesc: 'Use for advanced email copy generation.',
    claudeDesc: 'Use for smart sector analysis and summaries.',
    geminiDesc: 'Use for bulk web data analysis.',
    getApiKey: 'Get key',
    connected: 'Connected',
    notConnected: 'Not Connected',
    exportDestination: 'Export Destination',
    connectedAs: 'Connected as',
    manualLocation: 'Manual Location',
    googleDrive: 'Google Drive (Spreadsheets)',
    scraperSources: 'Scraper Sources',
    googleMaps: 'Google Maps',
    telefoonboek: 'Yellow Pages',
    kvk: 'Business Registry',
    addCustomSource: 'Add Custom Source',
    suggestions: 'Source Suggestions',
    automaticDiscovery: 'Automatic Discovery',
    savedSources: 'Saved Sources',
    enterUrl: 'Enter URL...',
    discoveryDesc: 'Let the bot find the best local directories automatically.',
    suggestedForYou: 'Recommended for you',
    highReliability: 'High Reliability',
    localDirectories: 'Local Business Directories',
    verifiedSource: 'Verified Source',
    dataQuality: 'Data Quality',
    premiumSource: 'Premium Database',
    leadEnrichment: 'Lead Enrichment',
    leadsWithMissingData: 'Leads with missing data',
    followUpPlanner: 'Follow-Up Planner',
    tabDataManagement: 'Data Management',
    action: 'Action',
    contactNow: 'Contact Now'
  },
  es: {
    dashboard: 'Panel',
    leads: 'Contactos',
    mailCampaigns: 'Campañas de Correo',
    settings: 'Ajustes',
    agenda: 'Agenda',
    addLead: 'Añadir Contacto',
    totalLeads: 'Prospectos Totales',
    activeLeads: 'Tratos Activos',
    conversionRate: 'Tasa de Conversión',
    searchPlaceholder: 'Buscar empresa o email...',
    upcoming: 'Próximamente',
    overdue: 'Atrasado',
    today: 'Hoy',
    agendaDescription: 'Administre aquí cuándo contactar a cada cliente.',
    quickTask: 'Añadir tarea rápida',
    companyPlaceholder: 'Buscar cliente...',
    taskPlaceholder: 'Ej. Llamar para oferta',
    agendaTaskLabel: '¿Qué hay que hacer?',
    pickDate: 'Fecha',
    pickTime: 'Hora',
    status: 'Etapa',
    actions: 'Acciones',
    allSectors: 'Todas las Industrias',
    new: 'Nuevo Prospecto',
    contacted: 'Contactado',
    interested: 'En Discusión',
    customer: 'Cliente Ganado',
    rejected: 'Cliente Perdido',
    showingResultFor: 'Mostrando resultado para',
    clearFilter: 'Limpiar filtro',
    upcomingTasks: 'Próximas Tareas',
    language: 'Idioma',
    dashboardDesc: 'Resumen de sus métricas de generación de leads y conversión.',
    recentActivity: 'Actividad Reciente',
    hotProspects: 'Prospectos Interesados',
    viewAll: 'Ver Todo',
    noProspects: 'Aún no hay prospectos. Añada algunos para verlos aquí.',
    company: 'Empresa',
    email: 'Correo',
    campaignsDesc: 'Diseñe secuencias automáticas y rastree su rendimiento.',
    createCampaign: 'Crear Campaña',
    totalSent: 'Total Enviados',
    avgOpenRate: 'Tasa de Apertura Prom.',
    avgClickRate: 'Tasa de Clics Prom.',
    totalReplies: 'Total de Respuestas',
    recentCampaigns: 'Campañas Recientes',
    campaignName: 'Nombre de Campaña',
    sentTo: 'Enviado A',
    openRate: 'Tasa de Apertura',
    clickRate: 'Tasa de Clics',
    dateRun: 'Ejecutado El',
    exportReport: 'Exportar Informe',
    duplicate: 'Duplicar',
    sendNow: 'Enviar Ahora',
    campaignInternalName: 'Nombre Interno de la Campaña',
    emailSubjectLine: 'Asunto del Correo',
    emailBody: 'Cuerpo del Correo',
    audienceSettings: 'Configuración de Audiencia',
    targetSector: 'Sector Objetivo',
    targetStatus: 'Estado Objetivo',
    estimatedAudience: 'Audiencia Estimada',
    scheduleDelivery: 'Programar Envío',
    saveDraft: 'Guardar Borrador',
    sendCampaign: 'Enviar Campaña',
    scheduleCampaign: 'Programar Campaña',
    performanceSummary: 'Resumen de Rendimiento',
    subjectLine: 'Asunto',
    targetSegments: 'Segmentos Objetivo',
    sendingAccount: 'Cuenta de Envío',
    tracking: 'Rastreo',
    emailsWillBeSent: 'Los correos se enviarán de inmediato a menos que se programen.',
    cancel: 'Cancelar',
    setDateAndTime: 'Configurar Fecha y Hora',
    leadsDesc: 'Gestione a sus clientes potenciales y siga su estado.',
    exportCsv: 'Exportar CSV',
    noLeadsFound: 'No se encontraron contactos',
    tryAdjustingSearch: 'Intente ajustar sus criterios de búsqueda o filtro.',
    settingsDesc: 'Gestione sus preferencias de cuenta y ajustes de la aplicación.',
    personalInformation: 'Información Personal',
    changeAvatar: 'Cambiar Avatar',
    firstName: 'Nombre',
    lastName: 'Apellido',
    emailAddress: 'Correo Electrónico',
    saveChanges: 'Guardar Cambios',
    apiKeys: 'Claves API',
    manageKeys: 'Gestione las claves para integraciones externas.',
    generateNewKey: 'Generar Nueva Clave',
    name: 'Nombre',
    tokenPreview: 'Vista Previa del Token',
    created: 'Creado',
    revoke: 'Revocar',
    edit: 'Editar',
    delete: 'Eliminar',
    pause: 'Pausar',
    resume: 'Reanudar',
    confirmDelete: '¿Está seguro de que desea eliminar este elemento?',
    targetAudiencePreview: 'Vista Previa del Público Objetivo',
    editCampaign: 'Editar Campaña',
    cancelSchedule: 'Cancelar Programación',
    tabProfile: 'Perfil',
    tabCompanyDetails: 'Detalles de Empresa',
    companyNameField: 'Nombre de la Empresa',
    websiteUrlField: 'URL del Sitio Web',
    logoUploadField: 'Subir Logo',
    logoUploadHelp: 'PNG, JPG o SVG (máx. 2MB).',
    addressField: 'Dirección Comercial',
    addressPlaceholder: 'Calle, Número, CP, Ciudad',
    phoneField: 'Número de Teléfono',
    vatField: 'Número de IVA',
    kvkField: 'Cámara de Comercio (KVK)',
    tabTeam: 'Miembros del Equipo',
    tabEmail: 'Correo y Entrega',
    tabNotifications: 'Notificaciones',
    tabLeadManagement: 'Gestión de Leads',
    tabBilling: 'Facturación y Uso',
    tabAutomation: 'Automatización y Bot',
    tabEmailNav: 'Correo y Entrega',
    tabAutomationNav: 'Automatización y Bot',
    emailConfig: 'Configuración de Correo SMTP',
    emailConfigDesc: 'Configure su servidor de correo saliente y su firma de correo electrónico.',
    smtpHost: 'Host SMTP',
    smtpPort: 'Puerto SMTP',
    senderName: 'Nombre del Remitente',
    defaultSignature: 'Firma de Correo Predeterminada',
    dailyLimit: 'Límite Diario de Envío',
    spamPrevention: 'Prevención de Spam (Acelerar envíos)',
    teamMembers: 'Miembros del Equipo',
    addMember: 'Añadir Miembro',
    role: 'Rol',
    admin: 'Administrador',
    viewer: 'Espectador',
    invite: 'Invitar',
    notificationsSettings: 'Preferencias de Notificación',
    emailOpens: 'Alerta de aperturas de correo',
    emailClicks: 'Alerta de clics en enlaces',
    weeklyReports: 'Resumen semanal',
    realTimeAlerts: 'Alertas en tiempo real',
    leadManagementOptions: 'Gestionar Etiquetas y Etapas',
    customSectors: 'Industrias Personalizadas (Sectores)',
    customStatuses: 'Estados Personalizados (Etapas)',
    addTag: 'Añadir Etiqueta',
    billing: 'Suscripción y Facturación',
    activePlan: 'Plan Activo',
    currentUsage: 'Uso Actual',
    emailsSentThisMonth: 'Correos enviados este mes',
    invoiceHistory: 'Historial de Facturas',
    automation: 'Automatización y Bot Scraper',
    scraperBot: 'Configuración del Web Scraper Bot',
    targetKeywords: 'Palabras Clave (separadas por comas)',
    cronSchedule: 'Programación de Scraper (Ej. C/miércoles a las 09:00)',
    autoVerify: 'Autenticar correos después de raspar',
    runScraper: 'Ejecutar Scraper Manualmente',
    replyToEmail: 'Correo de Respuesta',
    useSslTls: 'Usar Cifrado SSL/TLS',
    playPing: 'Tocar Melodía "Ping"',
    playChime: 'Tocar Melodía "Chime"',
    playPop: 'Tocar Melodía "Pop"',
    upgradePlan: 'Mejorar Plan',
    downloadPdf: 'Descargar PDF',
    amount: 'Monto',
    date: 'Fecha',
    paid: 'Pagado',
    basicMode: 'Modo Básico',
    advancedMode: 'Modo Avanzado',
    frequency: 'Frecuencia',
    time: 'Hora',
    daily: 'Diario',
    weekly: 'Semanal',
    monthly: 'Mensual',
    useProxy: 'Usar Proxy Rotativo',
    headlessBrowser: 'Correr en Segundo Plano (Headless)',
    aiIntegrations: 'Integraciones IA & Automatiación',
    apiKey: 'Clave API',
    openaiDesc: 'Generación avanzada de textos de correo.',
    claudeDesc: 'Para análisis y resúmenes de sector.',
    geminiDesc: 'Para análisis masivo de datos web.',
    getApiKey: 'Obtener Clave',
    connected: 'Conectado',
    notConnected: 'Desconectado',
    exportDestination: 'Destino de Exportación',
    connectedAs: 'Conectado como',
    manualLocation: 'Ubicación Manual',
    googleDrive: 'Google Drive (Hojas de cálculo)',
    scraperSources: 'Fuentes de Scraper',
    googleMaps: 'Google Maps',
    telefoonboek: 'Páginas Amarillas',
    kvk: 'Registro Mercantil',
    addCustomSource: 'Añadir Fuente Personalizada',
    suggestions: 'Sugerencias de Fuentes',
    automaticDiscovery: 'Descubrimiento Automático',
    savedSources: 'Fuentes Guardadas',
    enterUrl: 'Ingresar URL...',
    discoveryDesc: 'Deja que el bot encuentre los mejores directorios locales automáticamente.',
    suggestedForYou: 'Sugerido para ti',
    highReliability: 'Alta Fiabilidad',
    localDirectories: 'Directorios Locales',
    verifiedSource: 'Fuente Verificada',
    dataQuality: 'Calidad de Datos',
    premiumSource: 'Base de Datos Premium'
  },
  fr: {
    dashboard: 'Tableau de Bord',
    leads: 'Contacts',
    mailCampaigns: 'Campagnes d\'E-mail',
    settings: 'Paramètres',
    agenda: 'Agenda',
    upcoming: 'À venir',
    overdue: 'En retard',
    today: 'Aujourd\'hui',
    agendaDescription: 'Gérez ici quel client contacter et quand.',
    quickTask: 'Ajouter une Tâche Rapide',
    companyPlaceholder: 'Chercher client...',
    taskPlaceholder: 'ex. Rappeler pour devis',
    agendaTaskLabel: 'Que faut-il faire ?',
    pickDate: 'Date',
    pickTime: 'Heure',
    addAsNew: 'ajouter comme nouveau client',
    createNewLead: 'Créer nouveau prospect',
    completeTask: 'Terminer',
    noTasks: 'Aucune tâche prévue',
    reminders: 'Rappels',
    notifications: 'Notifications',
    reminder30m: 'Rappel : Tâche dans 30 minutes !',
    reminderNow: 'Rappel : L\'heure de la tâche est arrivée !',
    addLead: 'Nouveau Contact',
    totalLeads: 'Total des Prospectus',
    activeLeads: 'Affaires Actives',
    conversionRate: 'Taux de Conversion',
    searchPlaceholder: 'Rechercher entreprise ou e-mail...',
    sector: 'Secteur',
    status: 'Étape',
    actions: 'Actions',
    allSectors: 'Tous les Secteurs',
    new: 'Nouveau Prospect',
    contacted: 'Contacté',
    interested: 'En Discussion',
    customer: 'Client Gagné',
    rejected: 'Intérêt Perdu',
    language: 'Langue',
    dashboardDesc: 'Aperçu de vos indicateurs de génération de leads et de conversion.',
    recentActivity: 'Activité Récente',
    hotProspects: 'Prospects Chauds',
    viewAll: 'Tout Voir',
    noProspects: 'Pas encore de prospects. Ajoutez-en pour les voir ici.',
    company: 'Entreprise',
    email: 'E-mail',
    campaignsDesc: 'Concevez des séquences automatiques et suivez les performances.',
    createCampaign: 'Créer une Campagne',
    totalSent: 'Total Envoyé',
    avgOpenRate: 'Taux d\'Ouverture Moyen',
    avgClickRate: 'Taux de Clic Moyen',
    totalReplies: 'Total des Réponses',
    recentCampaigns: 'Campagnes Récentes',
    campaignName: 'Nom de la Campagne',
    sentTo: 'Envoyé à',
    openRate: 'Taux d\'Ouverture',
    clickRate: 'Taux de Clic',
    dateRun: 'Date d\'Exécution',
    exportReport: 'Exporter le Rapport',
    duplicate: 'Dupliquer',
    sendNow: 'Envoyer Maintenant',
    campaignInternalName: 'Nom Interne de la Campagne',
    emailSubjectLine: 'Objet de l\'E-mail',
    emailBody: 'Corps de l\'E-mail',
    audienceSettings: 'Paramètres d\'Audience',
    targetSector: 'Secteur Cible',
    targetStatus: 'Statut Cible',
    estimatedAudience: 'Audience Estimée',
    scheduleDelivery: 'Programmer l\'Envoi',
    saveDraft: 'Enregistrer le Brouillon',
    sendCampaign: 'Envoyer la Campagne',
    scheduleCampaign: 'Programmer la Campagne',
    performanceSummary: 'Résumé des Performances',
    subjectLine: 'Objet',
    targetSegments: 'Segments Cibles',
    sendingAccount: 'Compte d\'Envoi',
    tracking: 'Suivi',
    emailsWillBeSent: 'Les e-mails seront envoyés immédiatement.',
    cancel: 'Annuler',
    setDateAndTime: 'Définir la Date et l\'Heure',
    leadsDesc: 'Gérez vos clients potentiels et suivez leur statut.',
    exportCsv: 'Exporter CSV',
    noLeadsFound: 'Aucun contact trouvé',
    tryAdjustingSearch: 'Essayez d\'ajuster vos critères de recherche.',
    settingsDesc: 'Gérez vos préférences de compte et paramètres de l\'application.',
    personalInformation: 'Informations Personnelles',
    changeAvatar: 'Changer l\'Avatar',
    firstName: 'Prénom',
    lastName: 'Nom',
    emailAddress: 'Adresse E-mail',
    saveChanges: 'Enregistrer les Modifications',
    apiKeys: 'Clés API',
    manageKeys: 'Gérer les clés pour les intégrations externes.',
    generateNewKey: 'Générer une Nouvelle Clé',
    name: 'Nom',
    tokenPreview: 'Aperçu du Token',
    created: 'Créé',
    revoke: 'Révoquer',
    edit: 'Modifier',
    delete: 'Supprimer',
    pause: 'Mettre en Pause',
    resume: 'Reprendre',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cet élément ?',
    targetAudiencePreview: 'Aperçu du Public Cible',
    editCampaign: 'Modifier la Campagne',
    cancelSchedule: 'Annuler la Programmation',
    tabProfile: 'Profil',
    tabCompanyDetails: 'Détails de l\'Entreprise',
    companyNameField: 'Nom de l\'Entreprise',
    websiteUrlField: 'URL du Site Web',
    logoUploadField: 'Télécharger le Logo',
    logoUploadHelp: 'PNG, JPG ou SVG (max. 2 Mo).',
    addressField: 'Adresse Commerciale',
    addressPlaceholder: 'Rue, Numéro, Code Postal, Ville',
    phoneField: 'Numéro de Téléphone',
    vatField: 'Numéro de TVA',
    kvkField: 'Registre du Commerce',
    tabTeam: 'Membres de l\'Équipe',
    tabEmail: 'E-mail et Livraison',
    tabNotifications: 'Notifications',
    tabLeadManagement: 'Gestion des Leads',
    tabBilling: 'Facturation et Utilisation',
    tabAutomation: 'Automatisation & Bot',
    tabEmailNav: 'E-mail et Livraison',
    tabAutomationNav: 'Automatisation & Bot',
    emailConfig: 'Configuration SMTP',
    emailConfigDesc: 'Configurez votre serveur de messagerie sortant et votre signature e-mail.',
    smtpHost: 'Hôte SMTP',
    smtpPort: 'Port SMTP',
    senderName: 'Nom de l\'Expéditeur',
    defaultSignature: 'Signature E-mail par Défaut',
    dailyLimit: 'Limite Quotidienne',
    spamPrevention: 'Prévention du Spam (Ralentir l\'envoi)',
    teamMembers: 'Membres de l\'Équipe',
    addMember: 'Ajouter un Membre',
    role: 'Rôle',
    admin: 'Administrateur',
    viewer: 'Spectateur',
    invite: 'Inviter',
    notificationsSettings: 'Préférences de Notification',
    emailOpens: 'Alerte d\'ouverture d\'e-mail',
    emailClicks: 'Alerte de clics sur les liens',
    weeklyReports: 'Rapport résumé hebdomadaire',
    realTimeAlerts: 'Alertes en temps réel pour lead chaud',
    leadManagementOptions: 'Gérer les Tags et Étapes',
    customSectors: 'Secteurs Personnalisés',
    customStatuses: 'Statuts Personnalisés',
    addTag: 'Ajouter un Tag',
    billing: 'Abonnement et Facturation',
    activePlan: 'Plan Actif',
    currentUsage: 'Utilisation Actuelle',
    emailsSentThisMonth: 'E-mails envoyés ce mois-ci',
    invoiceHistory: 'Historique des Factures',
    automation: 'Automatisation et Bot Scraper',
    scraperBot: 'Configuration du Web Scraper Bot',
    targetKeywords: 'Mots-clés cibles (séparés par virgule)',
    cronSchedule: 'Planification (Ex. chaque mercredi à 09:00)',
    autoVerify: 'Vérification automatique des e-mails après grattage',
    runScraper: 'Exécuter le Scraper Manuellement',
    replyToEmail: 'E-mail de Réponse',
    useSslTls: 'Utiliser le cryptage SSL/TLS',
    playPing: 'Jouer la mélodie "Ping"',
    playChime: 'Jouer la mélodie "Chime"',
    playPop: 'Jouer la mélodie "Pop"',
    upgradePlan: 'Plan de Mise à Niveau',
    downloadPdf: 'Télécharger PDF',
    amount: 'Montant',
    date: 'Date',
    paid: 'Payé',
    showingResultFor: 'Résultat pour',
    clearFilter: 'Effacer le filtre',
    upcomingTasks: 'Tâches à venir',
    basicMode: 'Mode Basique',
    advancedMode: 'Mode Avancé',
    frequency: 'Fréquence',
    time: 'Heure',
    daily: 'Quotidien',
    weekly: 'Hebdomadaire',
    monthly: 'Mensuel',
    useProxy: 'Utiliser un Proxy Rotatif',
    headlessBrowser: 'Exécuter en Arrière-plan (JS Rendering)',
    aiIntegrations: 'Intégrations IA & Automatisation',
    apiKey: 'Clé API',
    openaiDesc: 'Génération avancée de brouillons d\'e-mails.',
    claudeDesc: 'Analyse sectorielle intelligente et résumés.',
    geminiDesc: 'Analyse massive de données Web.',
    getApiKey: 'Obtenir la clé',
    connected: 'Connecté',
    notConnected: 'Non Connecté',
    exportDestination: 'Destination d\'Exportation',
    connectedAs: 'Connecté en tant que',
    manualLocation: 'Emplacement Manuel',
    googleDrive: 'Google Drive (Feuilles de calcul)',
    scraperSources: 'Sources du Scraper',
    googleMaps: 'Google Maps',
    telefoonboek: 'Pages Jaunes',
    kvk: 'Registre du Commerce',
    addCustomSource: 'Ajouter une Source Personnalisée',
    suggestions: 'Suggestions de Sources',
    automaticDiscovery: 'Découverte Automatique',
    savedSources: 'Sources Enregistrées',
    enterUrl: 'Entrer l\'URL...',
    discoveryDesc: 'Laissez le bot trouver automatiquement les meilleurs annuaires locaux.',
    suggestedForYou: 'Suggéré pour vous',
    highReliability: 'Hautes Fiabilité',
    localDirectories: 'Annuaires Locaux',
    verifiedSource: 'Source Vérifiée',
    dataQuality: 'Qualité des Données',
    premiumSource: 'Base de Données Premium'
  },
  de: {
    dashboard: 'Dashboard',
    leads: 'Kontakte',
    mailCampaigns: 'E-Mail Kampagnen',
    settings: 'Einstellungen',
    agenda: 'Agenda',
    upcoming: 'Anstehend',
    overdue: 'Überfällig',
    today: 'Heute',
    agendaDescription: 'Verwalten Sie hier, welchen Kunden Sie wann kontaktieren müssen.',
    quickTask: 'Schnelle Aufgabe hinzufügen',
    companyPlaceholder: 'Kunden suchen...',
    taskPlaceholder: 'z.B. Angebot nachfassen',
    agendaTaskLabel: 'Was ist zu tun?',
    pickDate: 'Datum',
    pickTime: 'Uhrzeit',
    addAsNew: 'als neuen Kunden hinzufügen',
    createNewLead: 'Neuen Lead erstellen',
    completeTask: 'Abschließen',
    noTasks: 'Keine Aufgaben geplant',
    reminders: 'Erinnerungen',
    notifications: 'Benachrichtigungen',
    reminder30m: 'Erinnerung: Aufgabe in 30 Minuten!',
    reminderNow: 'Erinnerung: Aufgabenzeit erreicht!',
    addLead: 'Kontakt Hinzufügen',
    totalLeads: 'Gesamte Leads',
    activeLeads: 'Aktive Deals',
    conversionRate: 'Konversionsrate',
    searchPlaceholder: 'Firma oder E-Mail suchen...',
    sector: 'Branche',
    status: 'Phase',
    actions: 'Aktionen',
    allSectors: 'Alle Branchen',
    new: 'Neuer Lead',
    contacted: 'Kontaktiert',
    interested: 'In Besprechung',
    customer: 'Gewonnen',
    rejected: 'Verloren',
    language: 'Sprache',
    dashboardDesc: 'Übersicht Ihrer Lead-Generierungs- und Konversionskennzahlen.',
    recentActivity: 'Letzte Aktivitäten',
    hotProspects: 'Heiße Interessenten',
    viewAll: 'Alle ansehen',
    noProspects: 'Noch keine Interessenten. Fügen Sie welche hinzu.',
    company: 'Unternehmen',
    email: 'E-Mail',
    campaignsDesc: 'Automatisierte Sequenzen entwerfen und verfolgen.',
    createCampaign: 'Kampagne erstellen',
    totalSent: 'Gesamt gesendet',
    avgOpenRate: 'Durchschn. Öffnungsrate',
    avgClickRate: 'Durchschn. Klickrate',
    totalReplies: 'Gesamte Antworten',
    recentCampaigns: 'Neueste Kampagnen',
    campaignName: 'Kampagnenname',
    sentTo: 'Gesendet an',
    openRate: 'Öffnungsrate',
    clickRate: 'Klickrate',
    dateRun: 'Ausgeführt am',
    exportReport: 'Bericht Exportieren',
    duplicate: 'Duplizieren',
    sendNow: 'Jetzt Senden',
    campaignInternalName: 'Interner Kampagnenname',
    emailSubjectLine: 'E-Mail Betreff',
    emailBody: 'E-Mail Text',
    audienceSettings: 'Zielgruppen Einstellungen',
    targetSector: 'Zielbranche',
    targetStatus: 'Zielstatus',
    estimatedAudience: 'Geschätzte Zielgruppe',
    scheduleDelivery: 'Versand Planen',
    saveDraft: 'Entwurf Speichern',
    sendCampaign: 'Kampagne Senden',
    scheduleCampaign: 'Kampagne Planen',
    performanceSummary: 'Leistungs Zusammenfassung',
    subjectLine: 'Betreff',
    targetSegments: 'Zielsegmente',
    sendingAccount: 'Absenderkonto',
    tracking: 'Tracking',
    emailsWillBeSent: 'E-Mails werden sofort gesendet, sofern nicht geplant.',
    cancel: 'Abbrechen',
    setDateAndTime: 'Datum und Zeit einstellen',
    leadsDesc: 'Verwalten und verfolgen Sie Ihre Interessenten.',
    exportCsv: 'CSV Exportieren',
    noLeadsFound: 'Keine Kontakte gefunden',
    tryAdjustingSearch: 'Versuchen Sie, Ihre Suchkriterien anzupassen.',
    settingsDesc: 'Verwalten Sie Ihre Kontoeinstellungen und Präferenzen.',
    personalInformation: 'Persönliche Informationen',
    changeAvatar: 'Avatar ändern',
    firstName: 'Vorname',
    lastName: 'Nachname',
    emailAddress: 'E-Mail-Adresse',
    saveChanges: 'Änderungen speichern',
    apiKeys: 'API-Schlüssel',
    manageKeys: 'Schlüssel für externe Integrationen verwalten.',
    generateNewKey: 'Neuen Schlüssel Generieren',
    name: 'Name',
    tokenPreview: 'Token-Vorschau',
    created: 'Erstellt',
    revoke: 'Widerrufen',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    pause: 'Pausieren',
    resume: 'Fortsetzen',
    confirmDelete: 'Sind Sie sicher, dass Sie dies löschen möchten?',
    targetAudiencePreview: 'Zielgruppen Vorschau',
    editCampaign: 'Kampagne Bearbeiten',
    cancelSchedule: 'Planung Abbrechen',
    tabProfile: 'Profil',
    tabCompanyDetails: 'Unternehmensdetails',
    companyNameField: 'Unternehmensname',
    websiteUrlField: 'Webseite-URL',
    logoUploadField: 'Logo Hochladen',
    logoUploadHelp: 'PNG, JPG oder SVG (max. 2MB).',
    addressField: 'Geschäftsadresse',
    addressPlaceholder: 'Straße, Nummer, PLZ, Ort',
    phoneField: 'Telefonnummer',
    vatField: 'Umsatzsteuer-Nº',
    kvkField: 'Handelskammer',
    tabTeam: 'Teammitglieder',
    tabEmail: 'E-Mail & Versand',
    tabNotifications: 'Benachrichtigungen',
    tabLeadManagement: 'Lead Verwaltung',
    tabBilling: 'Abrechnung & Nutzung',
    tabAutomation: 'Automatisierung & Bot',
    tabEmailNav: 'E-Mail & Versand',
    tabAutomationNav: 'Automatisierung & Bot',
    emailConfig: 'SMTP E-Mail-Konfiguration',
    smtpHost: 'SMTP Host',
    smtpPort: 'SMTP Port',
    senderName: 'Absendername',
    defaultSignature: 'Standard E-Mail Signatur',
    dailyLimit: 'Tägliches Limit',
    spamPrevention: 'Spam Prävention (Versand drosseln)',
    teamMembers: 'Teammitglieder',
    addMember: 'Mitglied hinzufügen',
    role: 'Rolle',
    admin: 'Administrator',
    viewer: 'Betrachter',
    invite: 'Einladen',
    notificationsSettings: 'Benachrichtigungseinstellungen',
    emailOpens: 'Alarm bei E-Mail-Öffnungen',
    emailClicks: 'Alarm bei Linkklicks',
    weeklyReports: 'Wöchentliche Zusammenfassung',
    realTimeAlerts: 'Echtzeitalarme für heiße Leads',
    leadManagementOptions: 'Tags und Phasen verwalten',
    customSectors: 'Benutzerdefinierte Branchen',
    customStatuses: 'Benutzerdefinierte Status',
    addTag: 'Tag hinzufügen',
    billing: 'Abonnement & Abrechnung',
    activePlan: 'Aktiver Plan',
    currentUsage: 'Aktuelle Nutzung',
    emailsSentThisMonth: 'Gesendete E-Mails (dieser Monat)',
    invoiceHistory: 'Rechnungsverlauf',
    automation: 'Automatisierung & Web-Scraper',
    scraperBot: 'Web-Scraper Bot-Konfiguration',
    targetKeywords: 'Ziel-Keywords (kommagetrennt)',
    cronSchedule: 'Zeitplan (z.B. jeden Mi um 09:00)',
    autoVerify: 'E-Mails automatisch verifizieren nach dem Scraping',
    runScraper: 'Scraper Starten',
    replyToEmail: 'Antwort-E-Mail',
    useSslTls: 'SSL/TLS-Verschlüsselung verwenden',
    playPing: 'Spiele "Ping"',
    playChime: 'Spiele "Chime"',
    playPop: 'Spiele "Pop"',
    upgradePlan: 'Plan Aktualisieren',
    downloadPdf: 'PDF Herunterladen',
    amount: 'Betrag',
    date: 'Datum',
    paid: 'Bezahlt',
    basicMode: 'Basis Modus',
    advancedMode: 'Erweiterter Modus',
    frequency: 'Häufigkeit',
    time: 'Zeit',
    daily: 'Täglich',
    weekly: 'Wöchentlich',
    monthly: 'Monatlich',
    useProxy: 'Rotierenden Proxy verwenden',
    headlessBrowser: 'Im Hintergrund (Headless) ausführen',
    aiIntegrations: 'KI Integrationen & Automatisierung',
    apiKey: 'API-Schlüssel',
    openaiDesc: 'Erweiterte E-Mail Texte generieren.',
    claudeDesc: 'Intelligente Branchenanalyse und Zusammenfassungen.',
    geminiDesc: 'Für Massendatenanalyse Web.',
    getApiKey: 'Schlüssel holen',
    connected: 'Verbunden',
    notConnected: 'Nicht Verbunden',
    exportDestination: 'Exportziel',
    connectedAs: 'Verbunden als',
    manualLocation: 'Manuelle Position',
    googleDrive: 'Google Drive (E-tablolar)',
    scraperSources: 'Scraper Quellen',
    googleMaps: 'Google Maps',
    telefoonboek: 'Branchenverzeichnis',
    kvk: 'Handelsregister',
    addCustomSource: 'Eigene Quelle hinzufügen',
    suggestions: 'Quellenvorschläge',
    automaticDiscovery: 'Automatische Entdeckung',
    savedSources: 'Gespeicherte Quellen',
    enterUrl: 'URL eingeben...',
    discoveryDesc: 'Der Bot findet automatisch die besten lokalen Verzeichnisse.',
    suggestedForYou: 'Für Sie empfohlen',
    highReliability: 'Hohe Zuverlässigkeit',
    localDirectories: 'Lokale Verzeichnisse',
    verifiedSource: 'Verifizierte Quelle',
    dataQuality: 'Datenqualität',
    premiumSource: 'Premium-Datenbank'
  },
  it: {
    dashboard: 'Dashboard',
    leads: 'Contatti',
    mailCampaigns: 'Campagne E-mail',
    settings: 'Impostazioni',
    agenda: 'Agenda',
    upcoming: 'Prossimo',
    overdue: 'In Scadenza',
    today: 'Oggi',
    quickTask: 'Aggiungi Attività Rapida',
    companyPlaceholder: 'Cerca cliente...',
    taskPlaceholder: 'es. Richiamare per preventivo',
    addAsNew: 'aggiungi come nuovo cliente',
    createNewLead: 'Crea nuovo prospect',
    completeTask: 'Completa',
    noTasks: 'Nessuna attività pianificata',
    reminders: 'Promemoria',
    notifications: 'Notifiche',
    reminder30m: 'Promemoria: Attività tra 30 minuti!',
    reminderNow: 'Promemoria: È ora dell\'attività!',
    addLead: 'Aggiungi Contatto',
    totalLeads: 'Prospect Totali',
    activeLeads: 'Trattative Attive',
    conversionRate: 'Tasso di Conversione',
    searchPlaceholder: 'Cerca azienda o email...',
    sector: 'Settore',
    status: 'Stato',
    actions: 'Azioni',
    allSectors: 'Tutti i Settori',
    new: 'Nuovo Prospect',
    contacted: 'Contattato',
    interested: 'In Discussione',
    customer: 'Vinto',
    rejected: 'Perso',
    language: 'Lingua',
    dashboardDesc: 'Panoramica delle metriche di generazione lead e conversione.',
    recentActivity: 'Attività Recente',
    hotProspects: 'Prospect Caldi',
    viewAll: 'Vedi Tutto',
    noProspects: 'Nessun prospect ancora. Aggiungine uno.',
    company: 'Azienda',
    email: 'E-mail',
    campaignsDesc: 'Progetta sequenze automatiche e monitora.',
    createCampaign: 'Crea Campagna',
    totalSent: 'Totale Inviati',
    avgOpenRate: 'Tasso di Apertura Medio',
    avgClickRate: 'Tasso di Clic Medio',
    totalReplies: 'Risposte Totali',
    recentCampaigns: 'Campagne Recenti',
    campaignName: 'Nome della Campagna',
    sentTo: 'Inviato a',
    openRate: 'Tasso Apertura',
    clickRate: 'Tasso Clic',
    dateRun: 'Eseguito Il',
    exportReport: 'Esporta Rapporto',
    duplicate: 'Duplica',
    sendNow: 'Invia Subito',
    campaignInternalName: 'Nome Interno Campagna',
    emailSubjectLine: 'Oggetto E-mail',
    emailBody: 'Corpo dell\'E-mail',
    audienceSettings: 'Impostazioni Pubblico',
    targetSector: 'Settore Target',
    targetStatus: 'Stato Target',
    estimatedAudience: 'Pubblico Stimato',
    scheduleDelivery: 'Programma Invio',
    saveDraft: 'Salva Bozza',
    sendCampaign: 'Invia Campagna',
    scheduleCampaign: 'Programma Campagna',
    performanceSummary: 'Riepilogo Prestazioni',
    subjectLine: 'Oggetto',
    targetSegments: 'Segmenti Target',
    sendingAccount: 'Account Mittente',
    tracking: 'Tracciamento',
    emailsWillBeSent: 'Le email saranno inviate immediatamente se non programmate.',
    cancel: 'Annulla',
    setDateAndTime: 'Impostare Data e Ora',
    leadsDesc: 'Gestisci i tuoi potenziali clienti e segui il loro stato.',
    exportCsv: 'Esporta CSV',
    noLeadsFound: 'Nessun contatto trovato',
    tryAdjustingSearch: 'Prova a modificare i filtri.',
    settingsDesc: 'Gestisci le preferenze del tuo account e impostazioni app.',
    personalInformation: 'Informazioni Personali',
    changeAvatar: 'Cambia Avatar',
    firstName: 'Nome',
    lastName: 'Cognome',
    emailAddress: 'Indirizzo E-mail',
    saveChanges: 'Salva Modifiche',
    apiKeys: 'Chiavi API',
    manageKeys: 'Gestisci le integrazioni esterne.',
    generateNewKey: 'Genera Nuova Chiave',
    name: 'Nome',
    tokenPreview: 'Anteprima Token',
    created: 'Creato',
    revoke: 'Revoca',
    edit: 'Modifica',
    delete: 'Elimina',
    pause: 'Pausa',
    resume: 'Riprendi',
    confirmDelete: 'Sei sicuro di voler eliminare questo elemento?',
    targetAudiencePreview: 'Anteprima Pubblico',
    editCampaign: 'Modifica Campagna',
    cancelSchedule: 'Annulla Programmazione',
    tabProfile: 'Profilo',
    tabCompanyDetails: 'Dettagli Azienda',
    companyNameField: 'Nome dell\'Azienda',
    websiteUrlField: 'URL Sito Web',
    logoUploadField: 'Carica Logo',
    logoUploadHelp: 'PNG, JPG o SVG (max 2MB).',
    addressField: 'Indirizzo Commerciale',
    addressPlaceholder: 'Via, Numero, CAP, Città',
    phoneField: 'Numero di Telefono',
    vatField: 'Partita IVA',
    kvkField: 'Camera di Commercio',
    tabTeam: 'Membri Team',
    tabEmail: 'Email & Invio',
    tabNotifications: 'Notifiche',
    tabLeadManagement: 'Gestione Lead',
    tabBilling: 'Fatturazione',
    tabAutomation: 'Automazione & Bot',
    tabEmailNav: 'Email & Invio',
    tabAutomationNav: 'Automazione & Bot',
    emailConfig: 'Configurazione Email SMTP',
    smtpHost: 'Host SMTP',
    smtpPort: 'Porta SMTP',
    senderName: 'Nome Mittente',
    defaultSignature: 'Firma Predefinita',
    dailyLimit: 'Limite di Invio',
    spamPrevention: 'Prevenzione Spam (Rallenta invio)',
    teamMembers: 'Membri Team',
    addMember: 'Aggiungi Membro',
    role: 'Ruolo',
    admin: 'Amministratore',
    viewer: 'Spettatore',
    invite: 'Invita',
    notificationsSettings: 'Preferenze di Notifica',
    emailOpens: 'Avviso aperture email',
    emailClicks: 'Avviso clic sui link',
    weeklyReports: 'Rapporto settimanale',
    realTimeAlerts: 'Avvisi lead caldi tempo reale',
    leadManagementOptions: 'Gestisci Tag e Fasi',
    customSectors: 'Settori Personalizzati',
    customStatuses: 'Stati Personalizzati',
    addTag: 'Aggiungi Tag',
    billing: 'Abbonamento e Fatturazione',
    activePlan: 'Piano Attivo',
    currentUsage: 'Utilizzo Attuale',
    emailsSentThisMonth: 'Email inviate questo mese',
    invoiceHistory: 'Cronologia Fatture',
    automation: 'Automazione e Bot Scraper',
    scraperBot: 'Configurazione del Web Scraper Bot',
    targetKeywords: 'Parole Chiave (separate da virgola)',
    cronSchedule: 'Pianificazione (Es. ogni Mer alle 09:00)',
    autoVerify: 'Auto-verifica email dopo lo scraping',
    runScraper: 'Esegui Scraper Manualmente',
    replyToEmail: 'Email di Risposta',
    useSslTls: 'Usa Cifratura SSL/TLS',
    playPing: 'Suona "Ping"',
    playChime: 'Suona "Chime"',
    playPop: 'Suona "Pop"',
    upgradePlan: 'Cambia Piano',
    downloadPdf: 'Scarica PDF',
    amount: 'Importo',
    date: 'Data',
    paid: 'Pagato',
    basicMode: 'Modalità Base',
    advancedMode: 'Modalità Avanzata',
    frequency: 'Frequenza',
    time: 'Ora',
    daily: 'Giornaliero',
    weekly: 'Settimanale',
    monthly: 'Mensile',
    useProxy: 'Usa Proxy Rotanti',
    headlessBrowser: 'Esecuzione in Backg. (Headless)',
    aiIntegrations: 'Integrazioni IA & Automazione',
    apiKey: 'Chiavi API',
    openaiDesc: 'Per generazione testuale avanzata.',
    claudeDesc: 'Per analisi e riepiloghi smart settore.',
    geminiDesc: 'Per elaborazione dati web massiva.',
    getApiKey: 'Ottieni',
    connected: 'Connesso',
    notConnected: 'Non Connesso',
    exportDestination: 'Destinazione Esportazione',
    connectedAs: 'Connesso come',
    manualLocation: 'Posizione Manuale',
    googleDrive: 'Google Drive (Foglio di calcolo)',
    scraperSources: 'Sorgenti Scraper',
    googleMaps: 'Google Maps',
    telefoonboek: 'Pagine Gialle',
    kvk: 'Registro Imprese',
    addCustomSource: 'Aggiungi Sorgente Personalizzata',
    suggestions: 'Suggerimenti Sorgenti',
    automaticDiscovery: 'Scoperta Automatica',
    savedSources: 'Sorgenti Salvate',
    enterUrl: 'Inserisci URL...',
    discoveryDesc: 'Lascia che il bot trovi automaticamente le migliori directory locali.',
    suggestedForYou: 'Suggeriti per te',
    highReliability: 'Alta Affidabilità',
    localDirectories: 'Directory Locali',
    verifiedSource: 'Sorgente Verificata',
    dataQuality: 'Qualità dei Dati',
    premiumSource: 'Database Premium'
  },
  pt: {
    dashboard: 'Painel',
    leads: 'Contatos',
    mailCampaigns: 'Campanhas de E-mail',
    settings: 'Configurações',
    agenda: 'Agenda',
    upcoming: 'Próximas',
    overdue: 'Atrasadas',
    today: 'Hoje',
    agendaDescription: 'Gerencie aqui quando entrar em contato com qual cliente.',
    quickTask: 'Adicionar tarefa rápida',
    companyPlaceholder: 'Buscar cliente...',
    taskPlaceholder: 'ex. Ligar para proposta',
    agendaTaskLabel: 'O que precisa ser feito?',
    pickDate: 'Data',
    pickTime: 'Hora',
    addAsNew: 'adicionar como novo cliente',
    createNewLead: 'Criar novo prospect',
    completeTask: 'Concluir',
    noTasks: 'Nenhuma tarefa agendada',
    reminders: 'Lembretes',
    notifications: 'Notificações',
    reminder30m: 'Lembrete: Tarefa em 30 minutos!',
    reminderNow: 'Lembrete: A hora da tarefa chegou!',
    addLead: 'Adicionar Contato',
    totalLeads: 'Prospects Totais',
    activeLeads: 'Negócios Ativos',
    conversionRate: 'Taxa de Conversão',
    searchPlaceholder: 'Buscar empresa ou e-mail...',
    sector: 'Setor',
    status: 'Status',
    actions: 'Ações',
    allSectors: 'Todos os Setores',
    new: 'Novo Prospect',
    contacted: 'Contatado',
    interested: 'Interessado',
    customer: 'Cliente',
    rejected: 'Rejeitado',
    language: 'Idioma',
    dashboardDesc: 'Visão geral de suas métricas de geração de leads e conversão.',
    recentActivity: 'Atividade Recente',
    hotProspects: 'Prospects Quentes',
    viewAll: 'Ver Tudo',
    noProspects: 'Nenhum prospect ainda. Adicione um para vê-lo aqui.',
    company: 'Empresa',
    email: 'E-mail',
    campaignsDesc: 'Projete sequências de alcance automatizadas e acompanhe o desempenho.',
    createCampaign: 'Criar Campanha',
    totalSent: 'Total Enviado',
    avgOpenRate: 'Taxa média de abertura',
    avgClickRate: 'Taxa média de cliques',
    totalReplies: 'Total de respostas',
    recentCampaigns: 'Campanhas Recentes',
    campaignName: 'Nome da Campanha',
    sentTo: 'Enviado para',
    openRate: 'Taxa de Abertura',
    clickRate: 'Taxa de Cliques',
    dateRun: 'Data de Execução',
    exportReport: 'Exportar Relatório',
    duplicate: 'Duplicar',
    sendNow: 'Enviar Agora',
    campaignInternalName: 'Nome Interno da Campanha',
    emailSubjectLine: 'Assunto do E-mail',
    emailBody: 'Corpo do E-mail',
    audienceSettings: 'Configurações de Público',
    targetSector: 'Setor Alvo',
    targetStatus: 'Status Alvo',
    estimatedAudience: 'Público Estimado',
    scheduleDelivery: 'Agendar Entrega',
    saveDraft: 'Salvar Rascunho',
    sendCampaign: 'Enviar Campanha',
    scheduleCampaign: 'Agendar Campanha',
    performanceSummary: 'Resumo de Desempenho',
    subjectLine: 'Assunto',
    targetSegments: 'Segmentos Alvo',
    sendingAccount: 'Conta de Envio',
    tracking: 'Rastreamento',
    emailsWillBeSent: 'Os e-mails serão enviados imediatamente, a menos que sejam agendados.',
    cancel: 'Cancelar',
    setDateAndTime: 'Configurar Data e Hora',
    leadsDesc: 'Gerencie seus leads e acompanhe o status deles.',
    exportCsv: 'Exportar CSV',
    noLeadsFound: 'Nenhum contato encontrado',
    tryAdjustingSearch: 'Tente ajustar sua busca ou filtros.',
    settingsDesc: 'Gerencie suas preferências de conta e configurações do app.',
    personalInformation: 'Informações Pessoais',
    changeAvatar: 'Alterar Avatar',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    emailAddress: 'Endereço de E-mail',
    saveChanges: 'Salvar Alterações',
    apiKeys: 'Chaves API',
    manageKeys: 'Gerencie chaves para integrações externas.',
    generateNewKey: 'Gerar Nova Chave',
    name: 'Nome',
    tokenPreview: 'Pré-visualização do Token',
    created: 'Criado',
    revoke: 'Revogar',
    edit: 'Editar',
    delete: 'Excluir',
    pause: 'Pausar',
    resume: 'Retomar',
    confirmDelete: 'Tem certeza que deseja excluir este item?',
    targetAudiencePreview: 'Pré-visualização do Público',
    editCampaign: 'Editar Campanha',
    cancelSchedule: 'Cancelar Agendamento',
    tabProfile: 'Perfil',
    tabCompanyDetails: 'Detalhes da Empresa',
    companyNameField: 'Nome da Empresa',
    websiteUrlField: 'URL do Site',
    logoUploadField: 'Upload de Logo',
    logoUploadHelp: 'PNG, JPG ou SVG (máx. 2MB).',
    addressField: 'Endereço Comercial',
    addressPlaceholder: 'Rua, Número, CEP, Cidade',
    phoneField: 'Número de Telefone',
    vatField: 'Número de IVA',
    kvkField: 'Câmara de Comércio',
    tabTeam: 'Membros da Equipe',
    tabEmail: 'E-mail e Entrega',
    tabNotifications: 'Notificações',
    tabLeadManagement: 'Gestão de Leads',
    tabBilling: 'Faturamento e Uso',
    tabAutomation: 'Automação e Bot',
    tabEmailNav: 'E-mail e Entrega',
    tabAutomationNav: 'Automação e Bot',
    emailConfig: 'Configurações de E-mail SMTP',
    smtpHost: 'Host SMTP',
    smtpPort: 'Porta SMTP',
    senderName: 'Nome do Remetente',
    defaultSignature: 'Assinatura Padrão',
    dailyLimit: 'Limite Diário',
    spamPrevention: 'Prevenção de Spam (Reduzir velocidade)',
    teamMembers: 'Membros da Equipe',
    addMember: 'Adicionar Membro',
    role: 'Papel',
    admin: 'Admin',
    viewer: 'Visualizador',
    invite: 'Convidar',
    notificationsSettings: 'Preferências de Notificação',
    emailOpens: 'Alerta abertura e-mail',
    emailClicks: 'Alerta cliques em links',
    weeklyReports: 'Resumo semanal',
    realTimeAlerts: 'Alertas em tempo real para lead quente',
    leadManagementOptions: 'Gerenciar Etiquetas e Fases',
    customSectors: 'Setores Personalizados',
    customStatuses: 'Status Personalizados',
    addTag: 'Adicionar Etiqueta',
    billing: 'Assinatura e Faturamento',
    activePlan: 'Plano Ativo',
    currentUsage: 'Uso Atual',
    emailsSentThisMonth: 'E-mails enviados este mês',
    invoiceHistory: 'Histórico de Faturas',
    automation: 'Automação e Bot Scraper',
    scraperBot: 'Configuração do Web Scraper Bot',
    targetKeywords: 'Palavras-chave (separadas por vírgula)',
    cronSchedule: 'Agendamento (Ex. toda Quarta às 09:00)',
    autoVerify: 'Auto-verificar e-mails após raspagem',
    runScraper: 'Executar Scraper Manualmente',
    replyToEmail: 'E-mail de Resposta',
    useSslTls: 'Usar SSL/TLS',
    playPing: 'Tocar "Ping"',
    playChime: 'Tocar "Chime"',
    playPop: 'Tocar "Pop"',
    upgradePlan: 'Melhorar Plano',
    downloadPdf: 'Baixar PDF',
    amount: 'Valor',
    date: 'Data',
    paid: 'Pago',
    basicMode: 'Modo Básico',
    advancedMode: 'Modo Avançado',
    frequency: 'Frequência',
    time: 'Hora',
    daily: 'Diário',
    weekly: 'Semanal',
    monthly: 'Mensal',
    useProxy: 'Usar Proxy Rotativo',
    headlessBrowser: 'Headless Browser (JS Rendering)',
    aiIntegrations: 'Integrações de IA & Automação',
    apiKey: 'Chave API',
    openaiDesc: 'Geração avançada de cópia de e-mail.',
    claudeDesc: 'Para análise e resumos inteligentes de setor.',
    geminiDesc: 'Para análise massiva de dados web.',
    getApiKey: 'Obter Chave',
    connected: 'Conectado',
    notConnected: 'Não Conectado',
    exportDestination: 'Destino de Exportação',
    connectedAs: 'Conectado como',
    manualLocation: 'Localização Manual',
    googleDrive: 'Google Drive (Planilhas)',
    scraperSources: 'Fontes de Scraper',
    googleMaps: 'Google Maps',
    telefoonboek: 'Páginas Amarelas',
    kvk: 'Registo Comercial',
    addCustomSource: 'Adicionar Fonte Personalizada',
    suggestions: 'Sugestões de Fontes',
    automaticDiscovery: 'Descoberta Automática',
    savedSources: 'Fontes Salvas',
    enterUrl: 'Digitar URL...',
    discoveryDesc: 'Deixe o bot encontrar automaticamente os melhores diretórios locais.',
    suggestedForYou: 'Sugerido para você',
    highReliability: 'Alta Confiabilidade',
    localDirectories: 'Diretórios Locais',
    verifiedSource: 'Fonte Verificada',
    dataQuality: 'Qualidade dos Dados',
    premiumSource: 'Base de Dados Premium'
  },
  tr: {
    dashboard: 'Gösterge Paneli',
    leads: 'Potansiyel Müşteriler',
    mailCampaigns: 'E-posta Kampanyaları',
    settings: 'Ayarlar',
    agenda: 'Ajanda',
    upcoming: 'Yaklaşan',
    overdue: 'Gecikmiş',
    today: 'Bugün',
    agendaDescription: 'Hangi gün hangi müşteriyle irtibata geçmen gerektiğini buradan yönet.',
    quickTask: 'Hızlı Görev Ekle',
    companyPlaceholder: 'Müşteri ara...',
    taskPlaceholder: 'Örn. Teklif için ara',
    agendaTaskLabel: 'Ne yapılacak?',
    pickDate: 'Tarih',
    pickTime: 'Saat',
    addAsNew: 'yeni müşteri olarak ekle',
    createNewLead: 'Yeni müşteri oluştur',
    completeTask: 'Tamamla',
    noTasks: 'Planlanmış görev yok',
    reminders: 'Hatırlatıcılar',
    notifications: 'Bildirimler',
    reminder30m: 'Hatırlatıcı: Görev 30 dakika içinde!',
    reminderNow: 'Hatırlatıcı: Görev zamanı geldi!',
    addLead: 'Yeni Kişi Ekle',
    totalLeads: 'Toplam Potansiyel',
    activeLeads: 'Aktif Fırsatlar',
    conversionRate: 'Kapanış Oranı',
    searchPlaceholder: 'Firma veya e-posta ara...',
    sector: 'Sektör',
    status: 'Aşama',
    actions: 'İşlemler',
    allSectors: 'Tüm Sektörler',
    new: 'Yeni Fırsat',
    contacted: 'İletişime Geçildi',
    interested: 'Görüşülüyor',
    customer: 'Kazanıldı',
    rejected: 'Kaybedildi',
    language: 'Dil',
    dashboardDesc: 'Müşteri kazanım ve dönüşüm metriklerinize genel bakış.',
    recentActivity: 'Son Aktiviteler',
    hotProspects: 'Sıcak Fırsatlar',
    viewAll: 'Tümünü Gör',
    noProspects: 'Henüz kişi yok. Başlamak için bir tane ekleyin.',
    company: 'Firma',
    email: 'E-posta',
    campaignsDesc: 'Otomatik erişim dizileri tasarlayın ve performanslarını izleyin.',
    createCampaign: 'Kampanya Oluştur',
    totalSent: 'Gönderilen',
    avgOpenRate: 'Ort. Açılma Oranı',
    avgClickRate: 'Ort. Tıklama Oranı',
    totalReplies: 'Toplam Yanıt',
    recentCampaigns: 'Son Kampanyalar',
    campaignName: 'Kampanya Adı',
    sentTo: 'Gönderilen Kişi',
    openRate: 'Açılma Oranı',
    clickRate: 'Tıklama Oranı',
    dateRun: 'Çalışma Tarihi',
    exportReport: 'Raporu Dışa Aktar',
    duplicate: 'Çoğalt',
    sendNow: 'Şimdi Gönder',
    campaignInternalName: 'Dahili Kampanya Adı',
    emailSubjectLine: 'E-posta Konu Satırı',
    emailBody: 'E-posta İçeriği',
    audienceSettings: 'Hedef Kitle Ayarları',
    targetSector: 'Hedef Sektör',
    targetStatus: 'Hedef Aşama',
    estimatedAudience: 'Tahmini Kitle',
    scheduleDelivery: 'Gönderimi Planla',
    saveDraft: 'Taslağı Kaydet',
    sendCampaign: 'Kampanyayı Gönder',
    scheduleCampaign: 'Kampanyayı Planla',
    performanceSummary: 'Performans Özeti',
    subjectLine: 'Konu Satırı',
    targetSegments: 'Hedef Segmentler',
    sendingAccount: 'Gönderen Hesap',
    tracking: 'İzleme',
    emailsWillBeSent: 'E-postalar planlanmadığı takdirde hemen gönderilecektir.',
    cancel: 'İptal',
    setDateAndTime: 'Tarih ve Saat Ayarla',
    leadsDesc: 'Potansiyel müşterilerinizi yönetin ve durumlarını takip edin.',
    exportCsv: 'CSV Dışa Aktar',
    noLeadsFound: 'Kişi bulunamadı',
    tryAdjustingSearch: 'Arama veya filtreleme kriterlerinizi değiştirmeyi deneyin.',
    settingsDesc: 'Hesap tercihlerinizi ve uygulama ayarlarınızı yönetin.',
    personalInformation: 'Kişisel Bilgiler',
    changeAvatar: 'Avatarı Değiştir',
    firstName: 'Ad',
    lastName: 'Soyad',
    emailAddress: 'E-posta Adresi',
    saveChanges: 'Değişiklikleri Kaydet',
    apiKeys: 'API Anahtarları',
    manageKeys: 'Harici sistem entegrasyonları için anahtarları yönetin.',
    generateNewKey: 'Yeni Anahtar Oluştur',
    name: 'İsim',
    tokenPreview: 'Token Önizleme',
    created: 'Oluşturulma',
    revoke: 'İptal Et',
    edit: 'Düzenle',
    delete: 'Sil',
    pause: 'Duraklat',
    resume: 'Devam Et',
    confirmDelete: 'Bu öğeyi silmek istediğinize emin misiniz?',
    targetAudiencePreview: 'Hedef Kitle Önizlemesi',
    editCampaign: 'Kampanyayı Düzenle',
    cancelSchedule: 'Zamanlamayı İptal Et',
    tabProfile: 'Profil',
    tabCompanyDetails: 'Şirket Bilgileri',
    companyNameField: 'Firma Adı',
    websiteUrlField: 'Web Sitesi URL',
    logoUploadField: 'Logo Yükle',
    logoUploadHelp: 'PNG, JPG veya SVG (maks. 2MB).',
    addressField: 'Şirket Adresi',
    addressPlaceholder: 'Sokak, Numara, Posta Kodu, Şehir',
    phoneField: 'Telefon Numarası',
    vatField: 'Vergi Numarası (KDV/VAT)',
    kvkField: 'Ticaret Odası (KVK) No',
    tabTeam: 'Takım Üyeleri',
    tabEmail: 'E-posta ve Teslimat',
    tabNotifications: 'Bildirimler',
    tabLeadManagement: 'Kişi Yönetimi',
    tabBilling: 'Fatura ve Kullanım',
    tabAutomation: 'Otomasyon ve Bot',
    tabEmailNav: 'E-posta ve Teslimat',
    tabAutomationNav: 'Otomasyon ve Bot',
    emailConfig: 'SMTP E-posta Yapılandırması',
    smtpHost: 'SMTP Sunucusu',
    smtpPort: 'SMTP Bağlantı Noktası',
    senderName: 'Gönderen Adı',
    defaultSignature: 'Varsayılan E-posta İmzası',
    dailyLimit: 'Günlük Gönderim Sınırı',
    spamPrevention: 'Spam Önlem (Hız sınırlama)',
    teamMembers: 'Takım Üyeleri',
    addMember: 'Üye Ekle',
    role: 'Rol',
    admin: 'Yönetici',
    viewer: 'İzleyici',
    invite: 'Davet Et',
    notificationsSettings: 'Bildirim Tercihleri',
    emailOpens: 'E-posta açılış uyarısı',
    emailClicks: 'Link tıklama uyarısı',
    weeklyReports: 'Haftalık özet raporu',
    realTimeAlerts: 'Sıcak müşteriler için anlık bildirim',
    leadManagementOptions: 'Etiket ve Aşamaları Yönet',
    customSectors: 'Özel Sektörler',
    customStatuses: 'Özel Durumlar',
    addTag: 'Etiket Ekle',
    billing: 'Abonelik ve Fatura',
    activePlan: 'Plan',
    currentUsage: 'Kullanım',
    emailsSentThisMonth: 'Bu ay gönderilen e-postalar',
    invoiceHistory: 'Fatura Geçmişi',
    automation: 'Otomasyon ve Scraper Bot',
    scraperBot: 'Web Scraper Yapılandırması',
    targetKeywords: 'Anahtar Kelimeler (virgülle ayırın)',
    cronSchedule: 'Zamanlama (Örn. Her Çarşamba 09:00)',
    autoVerify: 'Kazımadan sonra e-postaları doğrula',
    runScraper: 'Botu Başlat',
    replyToEmail: 'Yanıt Adresi',
    useSslTls: 'SSL/TLS Kullan',
    playPing: '"Ping" Çal',
    playChime: '"Chime" Çal',
    playPop: '"Pop" Çal',
    upgradePlan: 'Planı Güncelle',
    downloadPdf: 'PDF İndir',
    amount: 'Tutar',
    date: 'Tarih',
    paid: 'Ödendi',
    basicMode: 'Temel Mod',
    advancedMode: 'Gelişmiş Mod',
    frequency: 'Sıklık',
    time: 'Saat',
    daily: 'Günlük',
    weekly: 'Haftalık',
    monthly: 'Aylık',
    useProxy: 'Proxy Kullan',
    headlessBrowser: 'Arka Plan Tarayıcısı (Headless)',
    aiIntegrations: 'Yapay Zeka & Entegrasyonlar',
    apiKey: 'API Anahtarı',
    openaiDesc: 'Gelişmiş e-posta metni üretimi.',
    claudeDesc: 'Akıllı sektör analizi ve özetleme.',
    geminiDesc: 'Büyük ölçekli veri analizi.',
    getApiKey: 'Anahtarı Al',
    connected: 'Bağlı',
    notConnected: 'Bağlı Değil',
    exportDestination: 'Dışa Aktarma Hedefi',
    connectedAs: 'Bağlı hesap',
    manualLocation: 'Manuel Konum',
    googleDrive: 'Google Drive (Tablolar)',
    scraperSources: 'Kaynaklar',
    googleMaps: 'Google Haritalar',
    telefoonboek: 'Rehber Kaynakları',
    kvk: 'Ticaret Sicili (KVK)',
    addCustomSource: 'Özel Kaynak Ekle',
    suggestions: 'Kaynak Önerileri',
    automaticDiscovery: 'Otomatik Keşif',
    savedSources: 'Kayıtlı Kaynaklar',
    enterUrl: 'URL girin...',
    discoveryDesc: 'Botun yerel dizinleri otomatik bulmasına izin verin.',
    suggestedForYou: 'Sizin için önerilenler',
    highReliability: 'Yüksek Güvenilirlik',
    localDirectories: 'Yerel Dizinler',
    verifiedSource: 'Doğrulanmış Kaynak',
    dataQuality: 'Veri Kalitesi',
    premiumSource: 'Premium Veritabanı',
    leadEnrichment: 'Veri Zenginleştirme',
    leadsWithMissingData: 'Eksik verili kayıtlar',
    followUpPlanner: 'Takip Planlayıcı',
    tabDataManagement: 'Veri Yönetimi',
    action: 'İşlem',
    contactNow: 'Hemen Ulaş',
    noLogo: 'Logo Yok',
    cardHolder: 'Kart Sahibi',
    cardNumber: 'Kart Numarası',
    expiryDate: 'Son Kullanma Tarihi',
    paymentConfirmed: 'Ödeme Onaylandı',
    manageTeamDescription: 'Ekip üyelerinizin erişim seviyelerini yönetin.',
    notificationsDesc: 'Hangi işlemler için bildirim almak istediğinizi ayarlayın.',
    aiIntegrationsDesc: 'Akıllı e-posta üretimi için yapay zeka sağlayıcılarını bağlayın.',
    apiKeysDesc: 'API kullanımı için sistem erişim anahtarlarınızı yönetin.',
    dataExportDesc: 'Tüm sistem verilerinizin yedeğini indirin.'
  }
};


const authTranslations = {
  en: {
    loginTo: 'Log in to ',
    createAccountTitle: 'Create your account',
    welcomeBack: 'Welcome back! Please enter your details.',
    signUpTrial: 'Sign up to start your 14-day free trial.',
    signIn: 'Sign In',
    signUp: 'Sign Up',
    continueGoogle: 'Continue with Google',
    continueMicrosoft: 'Continue with Microsoft',
    continueApple: 'Continue with Apple',
    orEmail: 'OR EMAIL',
    fullName: 'Full Name',
    password: 'Password',
    forgot: 'Forgot?',
    createAccountBtn: 'Create Account',
    justLookingAround: 'Just looking around?',
    tryFreeDemo: 'Try Free Demo',
    errFullName: 'Please enter your full name.',
    errValidEmail: 'Please enter a valid email address.',
    errPasswordLen: 'Password must be at least 5 characters long.',
    errNoAccount: 'No account found with this email. Please sign up.',
    errWrongPassword: 'Incorrect password.',
    errAccountExists: 'An account with this email already exists.'
  },
  nl: {
    loginTo: 'Inloggen bij ',
    createAccountTitle: 'Maak uw account aan',
    welcomeBack: 'Welkom terug! Vul uw gegevens in.',
    signUpTrial: 'Meld u aan voor uw 14-daagse proefperiode.',
    signIn: 'Inloggen',
    signUp: 'Aanmelden',
    continueGoogle: 'Doorgaan met Google',
    continueMicrosoft: 'Doorgaan met Microsoft',
    continueApple: 'Doorgaan met Apple',
    orEmail: 'OF E-MAIL',
    fullName: 'Volledige Naam',
    password: 'Wachtwoord',
    forgot: 'Vergeten?',
    createAccountBtn: 'Account Aanmaken',
    justLookingAround: 'Kijkt u even rond?',
    tryFreeDemo: 'Probeer Gratis Demo',
    errFullName: 'Vul uw volledige naam in.',
    errValidEmail: 'Vul een geldig e-mailadres in.',
    errPasswordLen: 'Wachtwoord moet minimaal 5 tekens lang zijn.',
    errNoAccount: 'Geen account gevonden met deze e-mail. Meld u aan.',
    errWrongPassword: 'Onjuist wachtwoord.',
    errAccountExists: 'Er bestaat al een account met deze e-mail.'
  },
  es: {
    loginTo: 'Iniciar sesión en ',
    createAccountTitle: 'Crea tu cuenta',
    welcomeBack: '¡Bienvenido! Por favor, introduzca sus datos.',
    signUpTrial: 'Regístrese para iniciar su prueba gratuita de 14 días.',
    signIn: 'Iniciar Sesión',
    signUp: 'Registrarse',
    continueGoogle: 'Continuar con Google',
    continueMicrosoft: 'Continuar con Microsoft',
    continueApple: 'Continuar con Apple',
    orEmail: 'O CORREO',
    fullName: 'Nombre Completo',
    password: 'Contraseña',
    forgot: '¿Olvidado?',
    createAccountBtn: 'Crear Cuenta',
    justLookingAround: '¿Solo mirando?',
    tryFreeDemo: 'Probar Demo Gratis',
    errFullName: 'Por favor, introduzca su nombre completo.',
    errValidEmail: 'Por favor, introduzca un correo válido.',
    errPasswordLen: 'La contraseña debe tener al menos 5 caracteres.',
    errNoAccount: 'No se encontró cuenta. Regístrese.',
    errWrongPassword: 'Contraseña incorrecta.',
    errAccountExists: 'Ya existe una cuenta con este correo.'
  },
  fr: {
    loginTo: 'Se connecter à ',
    createAccountTitle: 'Créez votre compte',
    welcomeBack: 'Bon retour ! Entrez vos coordonnées.',
    signUpTrial: 'Inscrivez-vous pour votre essai gratuit de 14 jours.',
    signIn: 'Se connecter',
    signUp: 'S\'inscrire',
    continueGoogle: 'Continuer avec Google',
    continueMicrosoft: 'Continuer avec Microsoft',
    continueApple: 'Continuer avec Apple',
    orEmail: 'OU E-MAIL',
    fullName: 'Nom Complet',
    password: 'Mot de passe',
    forgot: 'Oublié ?',
    createAccountBtn: 'Créer un Compte',
    justLookingAround: 'Juste en train de regarder ?',
    tryFreeDemo: 'Essayer la Démo Gratuite',
    errFullName: 'Veuillez entrer votre nom complet.',
    errValidEmail: 'Veuillez entrer un e-mail valide.',
    errPasswordLen: 'Le mot de passe doit comporter au moins 5 caractères.',
    errNoAccount: 'Aucun compte trouvé. Veuillez vous inscrire.',
    errWrongPassword: 'Mot de passe incorrect.',
    errAccountExists: 'Un compte avec cet e-mail existe déjà.'
  },
  de: {
    loginTo: 'Anmelden bei ',
    createAccountTitle: 'Erstellen Sie Ihr Konto',
    welcomeBack: 'Willkommen zurück! Bitte Daten eingeben.',
    signUpTrial: 'Melden Sie sich an für die 14-tägige Testversion.',
    signIn: 'Anmelden',
    signUp: 'Registrieren',
    continueGoogle: 'Mit Google fortfahren',
    continueMicrosoft: 'Mit Microsoft fortfahren',
    continueApple: 'Mit Apple fortfahren',
    orEmail: 'ODER E-MAIL',
    fullName: 'Vollständiger Name',
    password: 'Passwort',
    forgot: 'Vergessen?',
    createAccountBtn: 'Konto erstellen',
    justLookingAround: 'Nur umschauen?',
    tryFreeDemo: 'Kostenlose Demo testen',
    errFullName: 'Bitte geben Sie Ihren Namen ein.',
    errValidEmail: 'Bitte gültige E-Mail eingeben.',
    errPasswordLen: 'Passwort muss mindestens 5 Zeichen lang sein.',
    errNoAccount: 'Kein Konto gefunden. Bitte registrieren.',
    errWrongPassword: 'Falsches Passwort.',
    errAccountExists: 'Ein Konto existiert bereits.'
  },
  it: {
    loginTo: 'Accedi a ',
    createAccountTitle: 'Crea il tuo account',
    welcomeBack: 'Bentornato! Inserisci i tuoi dati.',
    signUpTrial: 'Iscriviti per la prova gratuita di 14 giorni.',
    signIn: 'Accedi',
    signUp: 'Iscriviti',
    continueGoogle: 'Continua con Google',
    continueMicrosoft: 'Continua con Microsoft',
    continueApple: 'Continua con Apple',
    orEmail: 'O EMAIL',
    fullName: 'Nome Completo',
    password: 'Password',
    forgot: 'Dimenticata?',
    createAccountBtn: 'Crea Account',
    justLookingAround: 'Stai solo guardando?',
    tryFreeDemo: 'Prova Demo Gratuita',
    errFullName: 'Inserisci il tuo nome completo.',
    errValidEmail: 'Inserisci un\'email valida.',
    errPasswordLen: 'La password deve contenere almeno 5 caratteri.',
    errNoAccount: 'Nessun account trovato. Registrati.',
    errWrongPassword: 'Password errata.',
    errAccountExists: 'Un account esiste già.'
  },
  tr: {
    loginTo: 'Giriş Yap: ',
    createAccountTitle: 'Hesabınızı oluşturun',
    welcomeBack: 'Tekrar hoş geldiniz! Bilgilerinizi giriniz.',
    signUpTrial: '14 günlük ücretsiz deneme için kayıt olun.',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    continueGoogle: 'Google ile Devam Et',
    continueMicrosoft: 'Microsoft ile Devam Et',
    continueApple: 'Apple ile Devam Et',
    orEmail: 'VEYA E-POSTA',
    fullName: 'Ad Soyad',
    password: 'Şifre',
    forgot: 'Unuttum?',
    createAccountBtn: 'Hesap Oluştur',
    justLookingAround: 'Sadece göz mü atıyorsun?',
    tryFreeDemo: 'Ücretsiz Demo',
    errFullName: 'Lütfen adınızı ve soyadınızı girin.',
    errValidEmail: 'Lütfen geçerli bir e-posta adresi girin.',
    errPasswordLen: 'Şifre en az 5 karakter uzunluğunda olmalıdır.',
    errNoAccount: 'Bu e-postaya ait hesap bulunamadı. Lütfen kayıt olun.',
    errWrongPassword: 'Hatalı şifre.',
    errAccountExists: 'Bu e-posta adresiyle zaten bir hesap var.',
    tabEmailNav: 'E-posta ve Gönderim',
    tabAutomationNav: 'Otomasyon ve Bot',
    showingResultFor: 'Arama sonucu',
    clearFilter: 'Filtreyi temizle',
    upcomingTasks: 'Yaklaşan Görevler'
  }
};

// Merge dictionaries
Object.keys(translations).forEach(lang => {
  translations[lang] = { ...translations[lang], ...authTranslations[lang] };
});

export const languagesList = [
  { code: 'en', label: 'English' },
  { code: 'nl', label: 'Nederlands' },
  { code: 'de', label: 'Deutsch' },
  { code: 'fr', label: 'Français' },
  { code: 'es', label: 'Español' },
  { code: 'it', label: 'Italiano' },
  { code: 'tr', label: 'Türkçe' }
];

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem('fleettrack_lang');
    if (saved && translations[saved]) return saved;
    // Auto-detect device language ('en-US' -> 'en')
    const browserLang = navigator.language.split('-')[0];
    return translations[browserLang] ? browserLang : 'en';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem('fleettrack_lang', lang);
    }
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, languagesList }}>
      {children}
    </LanguageContext.Provider>
  );
};
